Add support for is_null and is_not_null operators
piotch/jQuery-QueryBuilder-Elasticsearch pull request #7
Opened 2016-10-26 18:18 UTC by jimf

2016-11-18 10:28 UTC, piotch commented
Hello I added a comment, I think that there is a case (OR query with is_null in a branch) that is not generated correctly. I propose to add the test below, let me know if you think this is correct. 

```
    QUnit.test("OR condition and null op", function (assert) {

        $b.queryBuilder({
            filters: basic_filters,
            rules: {
                condition: 'OR',
                rules: [
                    {id: 'name', field: 'name', operator: 'is_not_null'},
                    {id: 'price', field: 'price', operator: 'is_null'}
                ]
            }
        });

        assert.deepEqual(
            $b.queryBuilder('getESBool'),
            {"bool": {"should":[
                {"exists":{"field":"name"}},
                {"bool":{"must_not": {"exists": {"field":"price"}}}}
            ]}},
            'Should build a should query with a bool subquery'
        );

    });
```

2016-11-18 10:28 UTC, piotch requested changes

2016-11-18 10:28 UTC, piotch commented on query-builder-elasticsearch.js
> +                        } else if (rule.operator === 'is_null' || rule.operator === 'is_not_null') {
I think that this causes a bug when you do use a OR condition with one of the branches that uses the is_null (must not exist) operator. I made a test to show this.

```    
QUnit.test("OR condition and null op", function (assert) {

        $b.queryBuilder({
            filters: basic_filters,
            rules: {
                condition: 'OR',
                rules: [
                    {id: 'name', field: 'name', operator: 'is_not_null'},
                    {id: 'price', field: 'price', operator: 'is_null'}
                ]
            }
        });

        assert.deepEqual(
            $b.queryBuilder('getESBool'),
            {"bool": {"should":[
                {"exists":{"field":"name"}},
                {"bool":{"must_not": {"exists": {"field":"price"}}}}
            ]}},
            'Should build a should query with a bool subquery'
        );

    });
```

2016-11-18 10:29 UTC, piotch commented on query-builder-elasticsearch.js
> +                        } else if (rule.operator === 'is_null' || rule.operator === 'is_not_null') {
This said, do not hesitate to tell me if this incorrect, maybe there are different ways to translate an OR query.

2016-11-18 20:11 UTC, jimf commented on query-builder-elasticsearch.js
> +                        } else if (rule.operator === 'is_null' || rule.operator === 'is_not_null') {
Ah, yes, you're correct. Good catch. I'll update.

2016-11-18 20:41 UTC, jimf commented
@piotch Updated

2016-11-19 13:40 UTC, piotch approved these changes

2016-11-19 13:41 UTC, merged

2016-11-19 13:41 UTC, piotch commented
Great, thank you!